App.IndexRoute = Ember.Route.extend({
	model:function(){
		var self=this;
		$.ajax({
			'url':'session.php',
			'dataType':'json',
			'async':false,
			success:function(session){
				self.controllerFor('index').set('sessionId',session.session_id);
				$.ajax({
					'url':restUrl+'getMenu',
					'type':'POST',
					'dataType':'json',
					'async':false,
					success:function(data){
						self.controllerFor('index').set('leftMenu',data);
						self.controllerFor('index').set('isLoad',true);
						$.ajax({
							'url':restUrl+'getCurUser',
							'type':'POST',
							'dataType':'json',
							'async':false,
							'data':{
								'session_id':self.controllerFor('index').get('sessionId')
							},
							success:function(data){
								if(data.id)
								{
									self.controllerFor('index').set('curUser',data);
									self.controllerFor('user').set('curUser',data);
								}
							},
							error:function(data){
								console.log(data.responseJson.message);
							}
						})
					}
				});
			}
		});
		$.ajax({
			'url':restUrl+'getNationsList',
			'type':'POST',
			'dataType':'json',
			'async':false,
			'data':{
				'session_id':self.controllerFor('index').get('sessionId')
			},
			success:function(data){

				self.controllerFor('index').set('nationsArray',$.merge([{'id':0,"name":"Все"}],data));
			}
		});
		$.ajax({
			'url':restUrl+'getLeagueList',
			'type':'POST',
			'dataType':'json',
			'async':false,
			success:function(data){
				self.controllerFor('index').set('leagueArray',$.merge([{'id':0,"name":"Все"}],data));
			}
		});
		$.ajax({
            'url':restUrl+'getClubList',
            'type':'POST',
            'dataType':'json',
            'async':false,
            success:function(data){
                self.controllerFor('index').set('clubArray',$.merge([{'id':0,"name":"Все"}],data));
            }
        });
        $.ajax({
            'url':restUrl+'getUserList',
            'type':'POST',
            'dataType':'json',
            'async':false,
            success:function(data){
                self.controllerFor('index').set('userArray',$.merge([{'id':0,"login":"Все"}],data));
            }
        });
        $.ajax({
            'url':restUrl+'getPositionList',
            'type':'POST',
            'dataType':'json',
            'async':false,
            success:function(data){
                self.controllerFor('index').set('positionArray',$.merge([{"position":"Все"}],data));
            }
        });
        $.ajax({
            'url':restUrl+'getCountUnreadMessages',
            'type':'POST',
            'dataType':'json',
            'data':{
				'session_id':self.controllerFor('index').get('sessionId')
			},
            success:function(data){
                self.controllerFor('index').set('countUnreadMessages',data.count);
            }
        });
        return $.extend({}, this.controllerFor('index').get('defaultSearchValues'));
	}
});